config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :contracts

  resources :tenants

  devise_for :landlords

  root 'home#index'
  get 'dashboard' => 'dashboard#index'
  get 'sms' => 'sms#index'

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :landlord
  belongs_to :tenant
  def description
    "Tenant: #{tenant.telephone} Period: #{start_date} - #{end_date}"
  end
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :contract
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?
  private
  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:telephone, :name,
                                    :email, :password, :password_confirmation)}
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_landlord!

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:landlord_id, :tenant_id, :payment_due_date, :start_date, :end_date, :credit_union)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_landlord!
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_landlord!

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:contract_id, :full)
    end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  require 'clockwork'
  def index
    logger.info sms_params
    @tenant = Tenant.find_by(telephone: sms_params[:from])
    if @tenant.present?
      logger.info "VALID TENANT"
    else
      logger.info "INVALID TENANT"
    end
    landlord_tel = sms_params[:content].to_s.split.last
    sms_landlord(@tenant, landlord_tel)
    render text: 'OK'
  end
  private
  def sms_params
    params.permit(:id, :to, :from, :keyword, :content)
  end

  def sms_landlord(tenant=nil, landlord)
    api = Clockwork::API.new(ENV['CLOCKWORK'])
    if tenant.present?
      content = "#{tenant.telephone} is a valid member"
    else
      content = "Tenant is not a valid member"
    end
    message = api.messages.build( :to => landlord, :content => content )
    response = message.deliver

    if response.success
      puts response.message_id
    else
      puts response.error_code
      puts response.error_description
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_landlord!

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :landlord_id, value: current_landlord.id %>
  <div class="field">
    <%= f.label :tenant_id %><br>
    <%= f.collection_select :tenant_id, Tenant.all, :id, :telephone %>
  </div>
  <div class="field">
    <%= f.label :payment_due_date %><br>
    <%= f.select :payment_due_date, 1..31 %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :credit_union %><br>
    <%= f.number_field :credit_union %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<h1>Listing contracts</h1>

<table>
  <thead>
    <tr>
      <th>Landlord</th>
      <th>Tenant</th>
      <th>Payment due date</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Credit union</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.landlord.name %></td>
        <td><%= contract.tenant.telephone %></td>
        <td><%= contract.payment_due_date %></td>
        <td><%= contract.start_date %></td>
        <td><%= contract.end_date %></td>
        <td><%= contract.credit_union %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Landlord:</strong>
  <%= @contract.landlord.name %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @contract.tenant.telephone %>
</p>

<p>
  <strong>Payment due date:</strong>
  <%= @contract.payment_due_date %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @contract.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @contract.end_date %>
</p>

<p>
  <strong>Credit union:</strong>
  <%= @contract.credit_union %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/dashboard/index.html.slim
h1 Landlord's data
p = link_to 'Manage tenants', tenants_path
p = link_to 'Manage contracts', contracts_path
p = link_to 'Manage payments', payments_path

app/views/home/index.html.slim
h1 Social Rent Tracker
= link_to 'Sign in', dashboard_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialRent</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

<footer>
<strong><%= link_to 'Back to Landlord dashboard', dashboard_path %>
</footer>
</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contract_id %><br>
    <%= f.collection_select :contract_id, Contract.where(landlord_id: current_landlord.id), :id, :description %>
  </div>
  <div class="field">
    <%= f.label :full %><br>
    <%= f.check_box :full %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Contract</th>
      <th>Full</th>
      <th>Date of payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.contract.description %></td>
        <td><%= payment.full %></td>
        <td><%= payment.created_at %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contract:</strong>
  <%= @payment.contract.description %>
</p>

<p>
  <strong>Full:</strong>
  <%= @payment.full %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>
  <% if @tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% @tenant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<h1>Listing tenants</h1>

<table>
  <thead>
    <tr>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.telephone %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render 'form' %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Telephone:</strong>
  <%= @tenant.telephone %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>